### ISSUE TITLE
logo design

### ISSUE THREAD

**Issue by reallinfo** [OmkarPathak/omkarpathak.github.io#6]
Hello @OmkarPathak 

I have designed a logo for your website upon your request. i combined code icon and initials of your name. What do you think about the logo?

![op](https://user-images.githubusercontent.com/36298335/47498073-d532b700-d864-11e8-9b29-8432a86d5a1d.jpg)

Web-site wiev

![op2](https://user-images.githubusercontent.com/36298335/47498094-debc1f00-d864-11e8-9ae6-7694472738df.png)

**Comment by OmkarPathak** [comment]
@reallinfo I liked the O and P parts. But its hard to relate the code part. Can u make it more intuitive?

**Comment by reallinfo** [comment]
Sure, I designed a new logo. I think concepts seem clearer in this logo. What do you think?

![op4](https://user-images.githubusercontent.com/36298335/47575493-e35b0300-d94a-11e8-841f-b15e60b65ac9.jpg)

**Comment by OmkarPathak** [comment]
@reallinfo seems like a thing :heart_eyes: white coloured font on the homepage looks really nice. Thank you very much :smile: Please open a PR

**Comment by reallinfo** [comment]
https://github.com/OmkarPathak/omkarpathak.github.io/pull/7

I sent a pr. I have also added logotype versions. maybe you need it... You can contact me if you need a graphic design. Goodworks!

**Comment by OmkarPathak** [comment]
@reallinfo yes I do need the graphic design.

**Comment by reallinfo** [comment]
if you have another repo, please open an issue and tag my username.
